name: dtd_impl
description: A server app using the shelf package and Docker.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/dtd_impl
publish_to: none

environment:
  sdk: ^3.3.0-152.0.dev

# Use 'any' constraints here; we get our versions from the DEPS file.
dependencies:
  shelf: any
  shelf_router: any
# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
# dev_dependencies:
#   http: any
#   lints: any
#   test: any
